### PR TITLE
Fix figures

### PR DESCRIPTION
**Pull request by tshiya731**
The main changes I made are:
1. fixed the figures problems in book 04
2. changed all the codes which insert the pictures, making the link into learn-python repository, so we won't lose the pictures again as long as the learn-python repository exists.
@rlanzafame

### CODE REVIEW

**Review by rlanzafame — CHANGES_REQUESTED** [review]
Great! Unfortunately I probably should have told you to use MyST admonitions rather than HTML tags, sorry. Luckily it is an easy fix, and good practice. Some comments and tips:
- see [this page](https://jupyterbook.org/en/stable/advanced/html.html#use-raw-html-in-markdown) where it explains that raw HTML is generally not advised
- see [this page](https://jupyterbook.org/en/stable/advanced/html.html#use-raw-html-in-markdown) which shows the preferred way to include images.
- experiment with the build locally and feel free to adjust the width/height to reach a formatting/image size that you think is good 
- once you commit more changes to this branch it will show up in the PR conversation and you can then re-request a review from me!

**Comment by tshiya731** [comment]
I changed the html into MyST format. @rlanzafame

**Comment by tshiya731** [comment]
Hi Robert, I changed all the html into MyST at the final commit: fix by MyST. @rlanzafame

**Review by rlanzafame — APPROVED** [review]

**Comment by rlanzafame** [comment]
great!

**Pull request merged**
