### PR TITLE
H5p test(only changed Exercise 1.2.2)

### PR DESCRIPTION
**Pull request by tshiya731**
(The changes are just made within book1 exercise 1.2.2)
The main changes I made are as follows:
1. I added a note "tags: jupyterquiz package" in the front of the package import part.
2. I added a note "tag: jupyterquiz--Exercise 1.2.2" in the front of display_quiz(questions[0]), and hided the jupyterquiz version of Exercise 1.2.2
3. I added the H5P version of Exercise 1.2.2.

However, I am not sure if the notes are correct/good enough in reaching the goal of organize the files. If it's not correct, can you please explain what will be a good way to add tags/notes?

Also, I am a bit confused about what should I summarize in a .md file. (which is demanded in the instructions from last week) @rlanzafame

### CODE REVIEW

**Comment by rlanzafame** [comment]
OK @tshiya731 I got a chance to look!

The tags are fine, although the `tags: ` text is unneeded. See the `docs/quizzes.md` file for my proposed convention. Look ok?

I think that this approach will be fine for helping keep track of things once we reorganize files and chapters. You can keep the `*.json` file in the original directory for the chapter and keep the commented cells with the `jupyterquiz-exercise-...` tags in place, which will allow anyone to trace back where they came from, if needed, for when the pages and chapters move around.

Here is an example of how you can see cell tags in VS Code:
image
Here is the tag in the import statement:
image

**Comment by rlanzafame** [comment]
I think you can set this up for the remainder of the exercises in Chapter 01 and let me know when i need to review again, then we can merge it. Then you can do it for all of the exercises.

**Comment by tshiya731** [comment]
Hi Robert, I made some changes within the commits:
1. All the jupyter-quiz in Chapter1 were converted into H5P now.
2. I added notes and tags for each jupyter-quiz in Chapter1.
3. I commented the import package part in Chapter1.
4. I completed the quizzes.md. I mainly added the website link of where H5P exercises are created and stored and added short description. However, I am not sure if it's enough.

@rlanzafame

**Review by rlanzafame — APPROVED** [review]
looks good!

**Pull request merged**
